#!/usr/bin/env bash

#redicts the server

sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "301 Moved Permanently" > /var/www/html/index.nginx-debian.html

sudo sed -i '24i\       rewrite ^/redirect_me ysamwel.tech permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
