#!/usr/bin/env bash
# A bash script that loops 10 times using while loop
# if, else and elif statement

script=0
while [ $script -lt 10 ]
do
    if [ $script -eq 3 ]; then
        echo "bad luck"
    elif [ $script -eq 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
        ((script++))
done

