#!/usr/bin/env bash
# A Bash script that displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
#
# Requirements:
# You must use the for loop (while and until are forbidden)
# Do not display hidden files


for file in *; 
do
    if [ ! -f "$file" ] || [[ "$file" == .* ]]; then
        continue
    fi
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)

    echo "$name_after_dash"
done
